### ISSUE TITLE
STOR-143 ⁃ Postcode lookup disable tabbing to hidden fields

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/storybook#218]
At the moment it's possible to tab to the hidden address fields.
Using the `hidden` attribute won't allow for autofilling the hidden fields, so think of a way to not tab to these fields. Tabindex perhaps?

**Comment by deniselashlley** [comment]
has been fixed

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
