### ISSUE TITLE
STOR-144 ⁃ PostcodeLookup line2 occasionally returns null

### ISSUE THREAD

**Issue by Heleen-cr** [comicrelief/storybook#219]
1. Some postcodes return "null" for line 2. This shows up as actual text in our dropdown and inputfields.

See https://lookups.sls.comicrelief.com/postcode/lookup?query=SW1P2DY
https://lookups.sls.comicrelief.com/postcode/lookup?query=B807DU

Put an extra check in for this.

2. We get a same key error in the console when the api is giving back results where the housename is left out. 
See: https://lookups.sls.comicrelief.com/postcode/lookup?query=W106HP 
This is a bug in the API.

**Comment by s-barrah** [comment]
https://github.com/comicrelief/serverless-lookups/pull/16
