### ISSUE TITLE
STOR-152 ⁃ New footer for comicrelief.com 

### ISSUE THREAD

**Issue by CarolineRennie** [comicrelief/storybook#236]
For the new comicrelief.com there is the need for a more structured footer as there is more varied content in the footer.

@LaBustaffa to add designs

**Comment by AndyEPhipps** [comment]
The need for the new TURBOFOOTER to exist in Storybook has yet to be defined (may only need to live in Drupal), will update accordingly

**Comment by LaBustaffa** [comment]
The designs are here: https://comicrelief.box.com/s/gf0d6xakdz2xro11n5k36qfmk36od48w
there's a meeting tomorrow to discuss.

**Comment by LaBustaffa** [comment]
The designs are here: https://comicrelief.box.com/s/gf0d6xakdz2xro11n5k36qfmk36od48w and 
there's a meeting tomorrow to discuss.

**Comment by AndyEPhipps** [comment]
Gonna close this and move over to the CR ticket, as this won't be a React component in SB

**Comment by CRSync** [comment]
➤ Unito Sync commented:

Transition made by Unito
