### ISSUE TITLE
Overflow search lookup

### ISSUE THREAD

**Issue by gusliedke** [comicrelief/storybook#29]
<img width="625" alt="screen shot 2017-09-19 at 14 43 30" src="https://user-images.githubusercontent.com/1434022/30595403-0113c506-9d49-11e7-821c-01277e5a5a11.png">

https://comicrelief.atlassian.net/browse/GP-912

**Comment by KoalaMango** [comment]
https://comicrelief.atlassian.net/browse/GP-912

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito
