### ISSUE TITLE
Provide menu fallback items

### ISSUE THREAD

**Issue by pvhee** [comicrelief/storybook#47]
We should provided fallback menu items if the menu back-end doesn't return items within 2 seconds. These fallback menu items should be able to be passed via props, but when not provided, we should have a set of default menu items (for the different footer menus).

**Comment by pvhee** [comment]
@KoalaMango do you see an immediate use of having the storybook component providing such functionality?

**Comment by KoalaMango** [comment]
@pvhee I think for user the `two seconds load` isn't ideal but probably okay. However, we need to consider fallback when api fails (no result returns). Currently Frost is using Storybook footer, it's helpful if it provides such functionality.

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito
