### ISSUE TITLE
Select address schools lookup is broken

### ISSUE THREAD

**Issue by gusliedke** [comicrelief/storybook#58]

**Comment by pvhee** [comment]
@AndyEPhipps is this still broken?

**Comment by AndyEPhipps** [comment]
Hm, it's working okay for me in the Step calculator, using the last version before 1.0.0.

Looking at the on the RND competition integration, it's not using a specific version of Storybook. I'm guessing updates came in and broke Gus' implementation of it.

As this is something that's still very much in development, I guess we really need to declare specific versions of SB components here onwards.

**Comment by pvhee** [comment]
@AndyEPhipps agreed - given that RND19 competition app won't need any further updates we can leave this without pushing further updates to it.

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito
