### ISSUE TITLE
Create Production Build

### ISSUE THREAD

**Issue by ayanozturk** [comicrelief/storybook#71]
Currently, the build file contains development version of react library, causing console warnings on production whenever a component from storybook is used

`Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.`

We need to build storybook with production config as described in the link.

**Comment by pvhee** [comment]
@ayanozturk I believe this was fixed? FYI If you do add `Fixes #71` at the top of your PR, this issue gets closed automatically when the PR is merged

**Comment by ayanozturk** [comment]
@pvhee yes, this issue is fixed. thanks for the tip, I'll try next time

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito
