### ISSUE TITLE
School lookup error message overlay manual edit link

### ISSUE THREAD

**Issue by KoalaMango** [comicrelief/storybook#86]
https://comicrelief.atlassian.net/browse/GP-909
<img width="252" alt="screen shot 2017-11-01 at 11 38 30" src="https://user-images.githubusercontent.com/6593407/32273199-5ec2255e-bef9-11e7-961f-c704c6859276.png">

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito
